# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=0, upload_to='static')),
                ('name', models.CharField(max_length=200)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Accesories',
        ),
        migrations.AlterField(
            model_name='hoodies',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
        migrations.AlterField(
            model_name='shirts',
            name='image',
            field=models.ImageField(default=0, upload_to='static'),
        ),
    ]
